# Generated by Django 6.1 on 2026-08-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('file_type', models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel Spreadsheet'), ('sample', 'Built-in Sample Data')], default='csv', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('column_schema', models.JSONField(default=dict, help_text='List of columns with inferred data types')),
                ('is_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('dark_modern', 'Dark Modern (Power BI Obsidian)'), ('powerbi_yellow', 'Power BI Classic (Yellow/Navy)'), ('cyberpunk', 'Cyberpunk Neon'), ('emerald', 'Teal & Emerald'), ('clean_light', 'Clean Slate Light')], default='dark_modern', max_length=50)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='analytics.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='analytics.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Visual', max_length=255)),
                ('visual_type', models.CharField(choices=[('bar', 'Bar Chart'), ('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('kpi', 'KPI Card'), ('table', 'Aggregated Matrix Table'), ('gauge', 'Gauge Target Chart'), ('slicer', 'Category Slicer')], default='bar', max_length=50)),
                ('x_axis', models.CharField(blank=True, max_length=255, null=True)),
                ('y_axis', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregation', models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('COUNT', 'Count'), ('MIN', 'Minimum'), ('MAX', 'Maximum')], default='SUM', max_length=20)),
                ('group_by', models.CharField(blank=True, max_length=255, null=True)),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('format_config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
            ],
        ),
    ]
