# Generated by Django 6.1 on 2026-08-07 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_dashboard_created_at_alter_dataset_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#00A4EF', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='column_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='query_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel Spreadsheet'), ('sample', 'Built-in Sample Data'), ('mongodb', 'MongoDB Database Server'), ('sql', 'SQL Relational Database'), ('api', 'REST API Endpoint')], default='csv', max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='analytics.datasettag'),
        ),
        migrations.CreateModel(
            name='DatasetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric (Float/Int)'), ('string', 'Categorical String'), ('datetime', 'Date & Time'), ('boolean', 'Boolean True/False')], default='string', max_length=20)),
                ('distinct_count', models.IntegerField(default=0)),
                ('null_count', models.IntegerField(default=0)),
                ('min_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_value', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_values', models.JSONField(blank=True, default=list)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='analytics.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DatasetSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('read', 'Read Only'), ('edit', 'Can Edit'), ('admin', 'Full Control')], default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='analytics.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dataset', 'user')},
            },
        ),
    ]
