# Generated by Django 6.1 on 2026-08-07 09:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_datasettag_dashboard_is_public_dashboard_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('SHARE', 'Share'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REFRESH', 'Refresh Data'), ('VIEW', 'View')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['position_y', 'position_x']},
        ),
        migrations.AlterUniqueTogether(
            name='datasetcolumn',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='datasetsharepermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='column_count',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='query_string',
        ),
        migrations.AddField(
            model_name='calculatedmeasure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='auto_refresh_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bookmarks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='filter_global',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid Layout'), ('freeform', 'Freeform'), ('story', 'Story Mode')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='template_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='version_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_quality_score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='dataset',
            name='database_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='missing_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataset',
            name='next_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='outlier_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='refresh_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='refresh_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='refresh_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='size_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='dataset',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='widget',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='widget',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widget',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='drilldown_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='widget',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='widget',
            name='parameter_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='widget',
            name='show_labels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='show_legend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='show_tooltips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='sort_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='sort_order',
            field=models.CharField(choices=[('ASC', 'Ascending'), ('DESC', 'Descending')], default='DESC', max_length=4),
        ),
        migrations.AddField(
            model_name='widget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='y_axis_secondary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='theme',
            field=models.CharField(choices=[('dark_modern', 'Dark Modern'), ('powerbi_yellow', 'Power BI Classic'), ('cyberpunk', 'Cyberpunk Neon'), ('emerald', 'Teal & Emerald'), ('clean_light', 'Clean Slate Light'), ('monochrome', 'Monochrome')], default='dark_modern', max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='column_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='datasets/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel Spreadsheet'), ('sample', 'Built-in Sample Data'), ('mongodb', 'MongoDB Database Server'), ('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('json', 'JSON File')], default='csv', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='tags',
        ),
        migrations.AlterField(
            model_name='datasetcolumn',
            name='data_type',
            field=models.CharField(default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='datasetsharepermission',
            name='permission_level',
            field=models.CharField(default='read', max_length=20),
        ),
        migrations.AlterField(
            model_name='widget',
            name='aggregation',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('COUNT', 'Count'), ('COUNT_DISTINCT', 'Count Distinct'), ('MIN', 'Minimum'), ('MAX', 'Maximum'), ('MEDIAN', 'Median'), ('STD', 'Standard Deviation')], default='SUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='widget',
            name='visual_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('kpi', 'KPI Card'), ('table', 'Aggregated Matrix Table'), ('gauge', 'Gauge Target Chart'), ('slicer', 'Category Slicer'), ('treemap', 'Treemap'), ('heatmap', 'Heatmap'), ('funnel', 'Funnel Chart'), ('waterfall', 'Waterfall Chart'), ('radar', 'Radar Chart'), ('boxplot', 'Box Plot'), ('histogram', 'Histogram')], default='bar', max_length=50),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['created_by', 'status'], name='analytics_d_created_13ebfb_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_public', 'view_count'], name='analytics_d_is_publ_0d8167_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['dashboard', 'visual_type'], name='analytics_w_dashboa_3349d6_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['created_by'], name='analytics_w_created_91c7a4_idx'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.organization'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.organization'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['status', 'created_at'], name='analytics_d_status_786302_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['created_by', 'is_public'], name='analytics_d_created_a413ac_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['file_type', 'status'], name='analytics_d_file_ty_232f85_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['refresh_status', 'next_refresh'], name='analytics_d_refresh_72bb86_idx'),
        ),
        migrations.RemoveField(
            model_name='datasetcolumn',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetsharepermission',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetsharepermission',
            name='user',
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_0aac6e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='analytics_a_resourc_a9d85c_idx'),
        ),
    ]
