# Generated by Django 6.1 on 2026-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_activitylog_organization_alter_dashboard_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='visual_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('column', 'Column Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('donut', 'Donut Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('kpi', 'KPI Card'), ('table', 'Aggregated Matrix Table'), ('gauge', 'Gauge Target Chart'), ('slicer', 'Category Slicer'), ('treemap', 'Treemap'), ('heatmap', 'Heatmap'), ('funnel', 'Funnel Chart'), ('waterfall', 'Waterfall Chart'), ('radar', 'Radar Chart'), ('boxplot', 'Box Plot'), ('histogram', 'Histogram')], default='scatter', max_length=50),
        ),
    ]
