# Generated by Django 6.1 on 2026-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
