# Generated by Django 6.1 on 2026-08-24 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_userprofile_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force user to reset password on next login.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_id',
            field=models.CharField(blank=True, help_text='Unique User ID (e.g. john.smith, EMP-1001). No spaces allowed.', max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='User ID may only contain letters, numbers, dots, hyphens, and underscores (no spaces or special characters).', regex='^[a-zA-Z0-9._-]+$')]),
        ),
    ]
